services:
  postgres:
    image: postgres:15
    container_name: dbm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "mairie"
      POSTGRES_USER: "db_admin"
      POSTGRES_PASSWORD: "CHANGE_ME"
      TZ: "Europe/Paris"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/app/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d mairie"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      -c shared_preload_libraries=pg_stat_statements
      -c track_activity_query_size=4096
      -c track_io_timing=on


  pgadmin:
    image: dpage/pgadmin4
    container_name: dbm-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "Europe/Paris"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.9.3-python3.11
    container_name: dbm-airflow
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://db_admin:CHANGE_ME@postgres:5432/mairie
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: "changeme_fernet_key"
      AIRFLOW__WEBSERVER__SECRET_KEY: "changeme_web_secret"
      AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
      TZ: "Europe/Paris"
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
      _AIRFLOW_WWW_USER_EMAIL: "admin@example.com"
      DBM_PG_HOST: "postgres"     
      DBM_PG_PORT: "5432"
      DBM_PG_DATABASE: "mairie"
      DBM_PG_USER: "db_admin"
      DBM_PG_PASSWORD: "CHANGE_ME"

    ports:
      - "8080:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./db/postgres:/opt/db-admin-ville-marseille/db/postgres
      - ./config:/opt/db-admin-ville-marseille/config
      - ./scripts:/opt/db-admin-ville-marseille/scripts
      - ./monitoring/status:/opt/db-admin-ville-marseille/monitoring/status
      - ./monitoring/reports:/opt/db-admin-ville-marseille/monitoring/reports
      - ./monitoring/kpi_definition.md:/opt/db-admin-ville-marseille/monitoring/kpi_definition.md

    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
          --role Admin
          --username admin
          --password admin
          --firstname Admin
          --lastname User
          --email admin@example.com || true &&
        airflow scheduler &
        airflow webserver
      "



  grafana:
    image: grafana/grafana:11.0.0
    container_name: dbm-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      TZ: "Europe/Paris"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
volumes:
  postgres_data:
  grafana_data:
